apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portainer-pv
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/portainer/data
volumeBindingMode: WaitForFirstConsumer