authentik:
  error_reporting:
    enabled: false

server:
  ingress:
    # Specify kubernetes ingress controller class name
    ingressClassName: traefik
    enabled: true
    hosts:
      - auth-staging.stonehaven.fr
redis:
  enabled: true