version: '3.3'
services:
  spring:
    image: ghcr.io/grayr0ot/sh-authentication-service:dev
    hostname: authentication-service
    networks:
      eureka_private:
    secrets:
     - jwt-public-key
     - jwt-private-key
     -
      source: mongo_database_config.yml
      target: mongo_database_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1.0'
          memory: 1024M

secrets:
  mongo_database_config.yml:
    external: true
  jwt-public-key:
    external: true
  jwt-private-key:
    external: true

networks:
  eureka_private:
    external: true
