version: '3.3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: stonehaven_staging
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=200'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
    secrets:
      - postgres_password
      - postgres_user
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.tcp.services.database-postgres.loadbalancer.server.port: '5432'
        traefik.tcp.routers.database-postgres.service: postgres
        traefik.tcp.routers.database-postgres.entrypoints: postgres
        traefik.constraint-label: traefik-public
        traefik.tcp.routers.database-tcp.rule: HostSNI(`*`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '2.0'
          memory: 4096M
        limits:
          cpus: '4.0'
          memory: 8192M
networks:
  default:
    driver: overlay
volumes:
  postgres:
    driver: local
secrets:
  postgres_password:
    external: true
  postgres_user:
    external: true
