version: '3.3'
services:
  mongodb:
    image: mongo
    hostname: sh_staging-database-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/sh_staging-mongodb-password
      MONGO_INITDB_DATABASE: staging
    networks:
      - host
      - sh_staging
    volumes:
      - mongodb:/data/db
    ports:
      - 57017:27017
    secrets:
      - sh_staging-mongodb-password
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
        limits:
          cpus: '2.0'
          memory: 2048M
  redis:
    image: redis
    hostname: sh_staging-database-redis
    networks:
      - sh_staging
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '0.25'
          memory: 256M
        limits:
          cpus: '0.5'
          memory: 512M
     
networks:
  host:
  sh_staging:
    external: true
volumes:
  mongodb:
    driver: local
secrets:
  sh_staging-mongodb-password:
    external: true
  sh_staging-ssh-password:
    external: true

