version: '3.3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: staging
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - host
    secrets:
      - mongodb_password
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
        limits:
          cpus: '2.0'
          memory: 2048M
networks:
  host:
volumes:
  mongodb:
    driver: local
secrets:
  mongodb_password:
    external: true
