version: '3.3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_DATABASE: staging
    volumes:
      - mongodb:/data/db
    secrets:
      - mongodb_password
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '1.0'
          memory: 1024M
        limits:
          cpus: '2.0'
          memory: 2048M
  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    environment:
      USER_PASSWORD_FILE: /run/secrets/sh_staging-ssh-password
      PASSWORD_ACCESS: "true"
      USER_NAME: stonehaven
    networks:
      - host
    ports:
      - 50022:2222
    secrets:
      - sh_staging-ssh-password
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 128M
        limits:
          cpus: '0.25'
          memory: 256M
     
networks:
  host:
volumes:
  mongodb:
    driver: local
secrets:
  mongodb_password:
    external: true
  sh_staging-ssh-password:
    external: true

