version: '3.3'
services:
  spring:
    image: ghcr.io/grayr0ot/sh-discord-bot:dev
    hostname: discord-bot
    environment:
      DISCORD_BOT_TOKEN: $DISCORD_BOT_TOKEN
      GITBOOK_API_TOKEN: $GITBOOK_API_TOKEN
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          cpus: '2.0'
          memory: 1024M
