version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-farmrun-item-service:dev
    networks:
      - sh_staging
      - host
    hostname: farmrun-item-service
    secrets:
     -
      source: sh_staging-mongo-database-config.yml
      target: mongo_database_config.yml
     -
      source: sh_staging-grpc_config
      target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          cpus: '2.0'
          memory: 1024M
networks:
  host:
  sh_staging:
    external: true
secrets:
  sh_staging-mongo-database-config.yml:
    external: true
  sh_staging-grpc_config:
    external: true
