version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-farmrun-item-service:dev
    networks:
      - minecraft_private
      - eureka_private
    hostname: farmrun-item-service
    secrets:
     -
      source: mongo_database_config.yml
      target: mongo_database_config.yml
     -
      source: grpc_config
      target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.farmrun-item-service-http.tls.certresolver: cf
        traefik.http.services.farmrun-item-service-grpc.loadbalancer.server.scheme: h2c
        traefik.http.middlewares.farmrun-item-service-grpc.grpcweb.allowOrigins: '*'
        traefik.http.routers.farmrun-item-service-http.service: farmrun-item-service-http
        traefik.http.routers.farmrun-item-service-grpc.tls: 'true'
        traefik.http.routers.farmrun-item-service-grpc.rule: Host(`farmrun-item-services-staging.stonehaven.fr`)
        traefik.http.routers.farmrun-item-service-grpc.entrypoints: https
        traefik.http.services.farmrun-item-service-http.loadbalancer.server.port: '8080'
        traefik.http.routers.farmrun-item-service-http.tls: 'true'
        traefik.http.services.farmrun-item-service-grpc.loadbalancer.server.port: '9090'
        traefik.http.routers.farmrun-item-service-http.rule: Host(`$DOMAIN`)
        traefik.http.routers.farmrun-item-service-http.entrypoints: https
        traefik.constraint-label: traefik-public
        traefik.http.routers.farmrun-item-service-grpc.service: farmrun-item-service-grpc
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.farmrun-item-service-grpc.tls.certresolver: cf
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          cpus: '2.0'
          memory: 1024M
networks:
  minecraft_private:
    external: true
  eureka_private:
    external: true
secrets:
  mongo_database_config.yml:
    external: true
  grpc_config:
    external: true
