version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-farmrun-player-service:dev
    hostname: farmrun-player-service
    networks:
       - sh_staging
    environment:
      PUBLIC_PATH: https://api-staging.stonehaven.fr
    secrets:
     -
      source: sh_staging-mongo-database-config.yml
      target: mongo_database_config.yml
     -
      source: grpc_config
      target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
          memory: 256M
        limits:
          cpus: '1.0'
          memory: 512M

networks:
  sh_staging:
    external: true

secrets:
  sh_staging-mongo-database-config.yml:
    external: true
  grpc_config:
    external: true
