version: '3.3'

services:
  paper:
    image: itzg/minecraft-server:latest
    networks:
      - default
      - minecraft_private
    environment:
      - TYPE=PAPER
      - VERSION=1.20.2
      - EULA=true
      - UID=1000
      - GID=1000
      - ENABLE_RCON=false
      - MEMORY=1G
      - TZ=Europe/Paris
      - GRPC_API_KEY=...
      - server_group=hub
      - SERVER_PORT=25565
      - DISABLE_HEALTHCHECK=true
    working_dir: /data
    volumes:
      - /home/stonehaven/servers/staging/staging_hub:/data
    logging:
      driver: json-file
    stdin_open: true
    tty: true

networks:
  default:
  minecraft_private:
    external: true
