version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-island-service:dev
    hostname: island-service
    environment:
      - ISLAND_SERVER_GROUP=island_group
    networks:
      - sh_staging
    environment:
      PUBLIC_PATH: https://api-staging.stonehaven.fr
    secrets:
     -
      source: sh_staging-mongo-database-config.yml
      target: mongo_database_config.yml
     -
      source: sh_staging-redis-database-config.yml
      target: redis_database_config.yml
     -
      source: sh_staging-grpc-config.yml
      target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
        limits:
          cpus: '1'
          memory: 1024M
networks:
  host:
  sh_staging:
    external: true
secrets:
  sh_staging-grpc-config.yml:
    external: true
  sh_staging-mongo-database-config.yml:
    external: true
  sh_staging-redis-database-config.yml:
    external: true
