version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-player-service:dev
    ports:
      - 9092:9090
    networks:
      - traefik-public
      - minecraft_private
    hostname: player-service
    secrets:
      -
        source: mongo_database_config.yml
        target: mongo_database_config.yml
      -
        source: grpc_config
        target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        traefik.http.routers.player-service-grpc.tls: 'true'
        traefik.http.routers.player-service-grpc.rule: Host(`$DOMAIN`)
        traefik.http.middlewares.player-service-grpc.grpcweb.allowOrigins: '*'
        traefik.http.routers.player-service-grpc.tls.certresolver: cf
        traefik.http.routers.player-service-grpc.entrypoints: https
        traefik.http.services.player-service-grpc.loadbalancer.server.port: '9090'
        traefik.http.services.player-service-grpc.loadbalancer.server.scheme: h2c
        traefik.constraint-label: traefik-public
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      resources:
        reservations:
          cpus: '0.5'
          memory: 256M
        limits:
          cpus: '1.0'
          memory: 512M
networks:
  traefik-public:
    external: true
  minecraft_private:
    external: true
secrets:
  mongo_database_config.yml:
    external: true
  grpc_config:
    external: true
