version: '3.3'
services:
  spring:
    image: ghcr.io/grayr0ot/sh-service-registry:dev
    hostname: service-registry
    networks:
      sh_staging:
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          cpus: '2.0'
          memory: 1024M
networks:
  sh_staging:
    external: true
