version: '3.3'
services:
  grpc:
    image: grayr0ot/sh-server-service:dev
    networks:
      - traefik-public
    secrets:
      -
        source: grpc_config
        target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.server-service-grpc.tls: 'true'
        traefik.http.services.server-service-grpc.loadbalancer.server.scheme: h2c
        traefik.http.middlewares.server-service-grpc.grpcweb.allowOrigins: '*'
        traefik.http.routers.server-service-grpc.rule: Host(`$DOMAIN`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.server-service-grpc.entrypoints: https
        traefik.http.routers.server-service-grpc.tls.certresolver: cf
        traefik.http.services.server-service-grpc.loadbalancer.server.port: '9090'
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
      resources:
        reservations:
          cpus: '0.5'
          memory: 256M
        limits:
          cpus: '1.0'
          memory: 512M
networks:
  traefik-public:
    external: true
secrets:
  grpc_config:
    external: true
