version: '3.3'
services:
  agent:
    image: swarmpit/agent:latest
    environment:
      DOCKER_API_VERSION: '1.35'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.05'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 64M
  app:
    image: swarmpit/swarmpit:latest
    environment:
      SWARMPIT_DB: http://db:5984
      SWARMPIT_INFLUXDB: http://influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-public
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.routers.swarmpit-https.entrypoints: https
        traefik.http.routers.swarmpit-https.tls.certresolver: cf
        traefik.http.services.swarmpit.loadbalancer.server.port: '8080'
        traefik.constraint-label: traefik-public
        traefik.http.routers.swarmpit-https.rule: Host(`$DOMAIN`)
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.swarmpit-https.tls: 'true'
      placement:
        constraints:
          - node.labels.swarmpit.node == true
      resources:
        reservations:
          cpus: '0.25'
          memory: 512M
        limits:
          cpus: '0.5'
          memory: 1024M
  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.swarmpit.node == true
      resources:
        reservations:
          cpus: '0.15'
          memory: 256M
        limits:
          cpus: '0.3'
          memory: 512M
  influxdb:
    image: influxdb:1.7
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.swarmpit.node == true
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
networks:
  net:
    driver: overlay
  traefik-public:
    external: true
volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
