version: '3.3'
services:
  traefik:
    image: traefik:v3.0
    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      - --providers.docker.exposedbydefault=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.le.acme.email=admin@stonehaven.fr
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      TRAEFIK_PASSWORD_HASH: /run/secrets/traefik_password_hash
      TRAEFIK_USER: admin
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    networks:
      - traefik-public
    secrets:
      - traefik_cf-dns-api-token
      - traefik_password_hash
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
        traefik.http.middlewares.admin-auth.basicauth.users: $TRAEFIK_USER:$TRAEFIK_PASSWORD_HASH
        traefik.http.routers.traefik-public-https.rule: Host(`traefik-staging.stonehaven.fr`)
        traefik.http.routers.traefik-public-https.tls: 'true'
        traefik.http.services.traefik-public.loadbalancer.server.port: '8080'
        traefik.http.routers.traefik-public-https.service: api@internal
        traefik.http.routers.traefik-public-http.middlewares: https-redirect
        traefik.http.routers.traefik-public-http.entrypoints: http
        traefik.http.routers.traefik-public-https.entrypoints: https
        traefik.http.middlewares.https-redirect.redirectscheme.permanent: 'true'
        traefik.constraint-label: traefik-public
        traefik.http.routers.traefik-public-http.rule: Host(`$DOMAIN`)
        traefik.http.routers.traefik-public-https.middlewares: admin-auth
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.traefik-public-https.tls.certresolver: cf
      placement:
        constraints:
          - node.labels.traefik.node == true
networks:
  traefik-public:
    external: true
volumes:
  traefik-public-certificates:
    driver: local
secrets:
  traefik_cf-dns-api-token:
    external: true
  traefik_password_hash:
    external: true
