apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stonehaven-staging
  name: database-postgres
  labels:
    environment: staging
    app: database-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-postgres
  template:
    metadata:
      name: database-postgres
      labels:
        app: database-postgres
    spec:
      containers:
        - name: database-postgres
          image: postgres
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-postgres
                  key: password
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: database-postgres
      restartPolicy: Always
      volumes:
        - name: database-postgres
          persistentVolumeClaim:
            claimName: database-postgres