apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: traefik
  name: traefik-pv
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/traefik/data
volumeBindingMode: WaitForFirstConsumer