apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: traefik
  name: traefik-pvc
spec:
  storageClassName: traefik-pv
  accessModes: [ ReadWriteOnce ]
  resources: {
    requests: {
      storage: 10Gi
    }
  }