apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stonehaven-staging
  name: service-registry
  labels:
    environment: staging
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      name: service-registry
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: ghcr.io/grayr0ot/sh-service-registry:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
