apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: service-registry
  labels:
    environment: staging
    app: service-registry
spec:
  selector:
    app: service-registry
  type: ClusterIP
  ports:
    - name: service-registry
      protocol: TCP
      port: 8761
      targetPort: 8761
  