apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: stonehaven-staging
  name: database-mongodb
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/stonehaven/staging/database/mongodb
volumeBindingMode: WaitForFirstConsumer