apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stonehaven-staging
  name: database-mongodb
spec:
  storageClassName: database-mongodb
  accessModes: [ ReadWriteOnce ]
  resources: {
    requests: {
      storage: 10Gi
    }
  }