apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stonehaven-staging
  name: database-mongodb-pvc
spec:
  storageClassName: database-mongodb-pv
  accessModes: [ ReadWriteOnce ]
  resources: {
    requests: {
      storage: 10Gi
    }
  }