apiVersion: v1
kind: Service
metadata:
  name: database-mongodb
spec:
  selector:
    app: database-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017
  type: NodePort
  