apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stonehaven-staging
  name: player-service
  labels:
    environment: staging
    app: player-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      name: player-service
      labels:
        app: player-service
    spec:
      containers:
        - name: player-service
          image: ghcr.io/grayr0ot/sh-player-service:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PUBLIC_PATH
              value: https://api-staging.stonehaven.fr
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: player-service
              mountPath: /config
      restartPolicy: Always
      volumes:
        - name: player-service
          secret:
            secretName: player-service