version: '3.3'
services:
  grpc:
    image: ghcr.io/grayr0ot/sh-farmrun-item-service:prod
    networks:
      - minecraft_private
      - eureka_private
    hostname: farmrun-item-service
    secrets:
     -
      source: sh_prod-mongo-database-config.yml
      target: mongo_database_config.yml
     -
      source: sh_prod-mongo-database-config.yml
      target: grpc_config.yml
    logging:
      driver: json-file
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '1.0'
          memory: 512M
        limits:
          cpus: '2.0'
          memory: 1024M
networks:
  sh_prod-minecraft-private:
    external: true
  sh_prod-eureka-private:
    external: true
secrets:
  sh_prod-mongo-database-config.yml:
    external: true
  sh_prod-mongo-database-config.yml:
    external: true
