apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: nexus
  name: nexus-pv
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/nexus/data
volumeBindingMode: WaitForFirstConsumer