apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: nexus
  name: nexus-pvc
spec:
  storageClassName: nexus-pv
  accessModes: [ ReadWriteOnce ]
  resources: {
    requests: {
      storage: 50Gi
    }
  }