apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: stonehaven-staging
  name: farmrun-mines
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/stonehaven/servers/staging/staging_mines
volumeBindingMode: WaitForFirstConsumer