version: '3.3'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/sh_prod-mongodb-password
      MONGO_INITDB_DATABASE: prod
    ports:
      - 17017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - host
    secrets:
      - sh_prod-mongodb-password
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.database.node == true
      resources:
        reservations:
          cpus: '2.0'
          memory: 4096M
        limits:
          cpus: '4.0'
          memory: 8192M
networks:
  host:
volumes:
  mongodb:
    driver: local
secrets:
  sh_prod-mongodb-password:
    external: true
