apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stonehaven-staging
  name: server-service
  labels:
    environment: staging
    app: server-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-service
  template:
    metadata:
      name: server-service
      labels:
        app: server-service
    spec:
      containers:
        - name: server-service
          image: ghcr.io/grayr0ot/sh-server-service:dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: server-service
              mountPath: /config
      restartPolicy: Always
      volumes:
        - name: server-service
          secret:
            secretName: server-service