apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: player-service
  labels:
    environment: staging
    app: player-service
spec:
  selector:
    app: player-service
  type: ClusterIP
  ports:
    - name: player-service
      protocol: TCP
      port: 8080
      targetPort: 8080
  