apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: server-service
  labels:
    environment: staging
    app: server-service
spec:
  selector:
    app: server-service
  type: ClusterIP
  ports:
    - name: server-service
      protocol: TCP
      port: 9090
      targetPort: 9090
  