apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: stonehaven-staging
  name: velocity-pv
provisioner: microk8s.io/hostpath
reclaimPolicy: Retain
parameters:
  pvDir: /home/stonehaven/servers/staging/staging_velocity
volumeBindingMode: WaitForFirstConsumer