apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: velocity
  labels:
    environment: staging
    app: velocity
spec:
  selector:
    app: velocity
  type: NodePort
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
      nodePort: 30655
  