apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: chat-service
  labels:
    environment: staging
    app: chat-service
spec:
  selector:
    app: chat-service
  type: ClusterIP
  ports:
    - name: chat-service-http
      protocol: TCP
      port: 8080
      targetPort: http
    - name: chat-service-grpc
      protocol: TCP
      port: 9090
      targetPort: grpc
