apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stonehaven-staging
  name: farmrun-spawn
  labels:
    environment: staging
    app: farmrun-spawn
spec:
  serviceName: farmrun-spawn
  replicas: 1
  selector:
    matchLabels:
      app: farmrun-spawn
  template:
    metadata:
      name: farmrun-spawn
      labels:
        app: farmrun-spawn
    spec:
      nodeSelector:
          kubernetes.io/hostname: ubuntu-2204-jammy-amd64-base
      containers:
        - name: farmrun-spawn
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1"
            limits:
              memory: "2048Mi"
              cpu: "2"
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: farmrun-spawn
              mountPath: /data
          env:
            - name: TYPE
              value: PAPER
            - name: PAPER_CHANNEL
              value: experimental
            - name: VERSION
              value: "1.21"
            - name: EULA
              value: "true"
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
            - name: TZ
              value: Europe/Paris
            - name: DISABLE_HEALTHCHECK
              value: "true"
            - name: HEALTH_USE_PROXY
              value: "true"
            - name: ENABLE_RCON
              value: "false"
            - name: REDIS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: farmrun-spawn
                  key: redis-hostname
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: farmrun-spawn
                  key: redis-port
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: farmrun-spawn
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: farmrun-spawn
                  key: redis-password
            - name: GRPC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: farmrun-spawn
                  key: grpc-api-key
            - name: HUB_SERVER_GROUP
              value: hub
            - name: SERVER_GROUP
              value: spawn
            - name: FARMRUN_SPAWN_SERVER_GROUP
              value: spawn
            - name: FARMRUN_GARDEN_SERVER_GROUP
              value: garden
            - name: FARMRUN_MINE_SERVER_GROUP
              value: mine
      restartPolicy: Always
      volumes:
        - name: farmrun-spawn
          persistentVolumeClaim:
            claimName: farmrun-spawn