apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: stonehaven-staging
  name: farmrun-spawn
spec:
  storageClassName: farmrun-spawn
  accessModes: [ ReadWriteOnce ]
  resources: {
    requests: {
      storage: 10Gi
    }
  }