apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: authentication-service
  labels:
    environment: staging
    app: authentication-service
spec:
  selector:
    app: authentication-service
  type: ClusterIP
  ports:
    - name: authentication-service
      protocol: TCP
      port: 8080
      targetPort: 8080
  