ingress:
  enabled: true
  ingressClassName: traefik
  pathType: ImplementationSpecific
  hostname: keycloak-staging.stonehaven.fr
  servicePort: http
  tls: true
postgresql:
  enabled: false
proxy: edge