apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: stonehaven-staging
  name: hub
  labels:
    environment: staging
    app: hub
spec:
  serviceName: hub
  replicas: 1
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      name: hub
      labels:
        app: hub
    spec:
      nodeSelector:
          kubernetes.io/hostname: ubuntu-2204-jammy-amd64-base
      containers:
        - name: hub
          image: amazoncorretto:21
          command:
            - "java"
            - "-jar"
            - "paper-1.21-25.jar"
          workingDir: /data
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "2048Mi"
              cpu: "1"
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - name: hub-pv
              mountPath: /data
          env:
            - name: TYPE
              value: PAPER
            - name: PAPER_CHANNEL
              value: experimental
            - name: VERSION
              value: "1.21"
            - name: EULA
              value: "true"
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
            - name: TZ
              value: Europe/Paris
            - name: DISABLE_HEALTHCHECK
              value: "true"
            - name: ENABLE_RCON
              value: "false"
            - name: REDIS_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: redis-hostname
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: redis-port
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: redis-password
            - name: GRPC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hub
                  key: grpc-api-key
            - name: HUB_SERVER_GROUP
              value: hub
            - name: SERVER_GROUP
              value: hub
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 300

      restartPolicy: Always
      volumes:
        - name: hub-pv
          persistentVolumeClaim:
            claimName: hub-pvc