apiVersion: v1
kind: Service
metadata:
  namespace: stonehaven-staging
  name: redis
  labels:
    environment: staging
    app: redis
spec:
  selector:
    app: redis-master
  type: NodePort
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30379